const router=require("express").Router();const {pool}=require("../config/db");
async function getHomepage(){const r=await pool.query("SELECT * FROM homepage_content WHERE id=1");return r.rows[0]||{};}
router.get("/",async(req,res,next)=>{try{const [home,s,p]=await Promise.all([getHomepage(),pool.query("SELECT s.*,sc.name category_name FROM services s LEFT JOIN service_categories sc ON sc.id=s.category_id WHERE s.is_active=true ORDER BY s.display_order,s.id LIMIT 8"),pool.query("SELECT p.*,pc.name category_name FROM projects p LEFT JOIN project_categories pc ON pc.id=p.category_id WHERE p.is_active=true ORDER BY p.id DESC LIMIT 6")]);res.render("home",{title:"Himalayan Geomatics Consultants",home,services:s.rows,projects:p.rows});}catch(e){next(e);}});
router.get("/services",async(req,res,next)=>{try{const r=await pool.query("SELECT s.*,sc.name category_name FROM services s LEFT JOIN service_categories sc ON sc.id=s.category_id WHERE s.is_active=true ORDER BY s.display_order,s.id");res.render("services",{title:"Our Services",services:r.rows});}catch(e){next(e);}});
router.get("/projects",async(req,res,next)=>{try{const r=await pool.query("SELECT p.*,pc.name category_name FROM projects p LEFT JOIN project_categories pc ON pc.id=p.category_id WHERE p.is_active=true ORDER BY p.created_at DESC,p.id DESC");res.render("projects",{title:"Our Projects",projects:r.rows});}catch(e){next(e);}});
router.get("/projects/:slug",async(req,res,next)=>{try{const [p,images]=await Promise.all([pool.query("SELECT p.*,pc.name category_name FROM projects p LEFT JOIN project_categories pc ON pc.id=p.category_id WHERE p.slug=$1 AND p.is_active=true LIMIT 1",[req.params.slug]),pool.query("SELECT * FROM project_images WHERE project_id=(SELECT id FROM projects WHERE slug=$1 LIMIT 1) ORDER BY display_order,id",[req.params.slug])]);if(!p.rows.length)return res.status(404).render("404",{title:"Project Not Found",message:"Project not found."});res.render("project-detail",{title:p.rows[0].title,project:p.rows[0],images:images.rows});}catch(e){next(e);}});
router.get("/gallery",async(req,res,next)=>{try{const r=await pool.query("SELECT * FROM gallery WHERE is_active=true ORDER BY display_order,id DESC");res.render("gallery",{title:"HGC Gallery",images:r.rows});}catch(e){next(e);}});
router.get("/contact",async(req,res,next)=>{try{const r=await pool.query("SELECT id,title FROM services WHERE is_active=true ORDER BY display_order,id");res.render("contact",{title:"Get a Quote | HGC",services:r.rows,success:req.query.success,error:req.query.error});}catch(e){next(e);}});
router.post("/contact",async(req,res,next)=>{try{const b=req.body;if(!b.name||!b.mobile||!b.message)return res.redirect("/contact?error=Please+fill+Name%2C+Mobile+and+Message");await pool.query("INSERT INTO contact_enquiries(name,email,mobile,company,service_id,message,status) VALUES($1,$2,$3,$4,$5,$6,'new')",[b.name.trim(),b.email||"",b.mobile.trim(),b.company||"",b.service_id||null,b.message.trim()]);res.redirect("/contact?success=1");}catch(e){next(e);}});
module.exports=router;
